name: catering
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  dartz: ^0.10.1
  device_info_plus: ^9.1.2
  dio: ^5.4.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  flutter_form_builder: ^9.2.1
  flutter_lints: ^3.0.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.10
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.9
  form_builder_validators: ^9.1.0
  get_it: ^7.6.7
  google_fonts: ^6.1.0
  image_picker: ^1.0.7
  intl: ^0.18.1
  lottie: ^3.0.0
  native_barcode_scanner: ^1.0.8
  permission_handler: ^11.2.0
  shared_preferences: ^2.2.2

dev_dependencies:
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:

  - assets/images/logo.svg
  